import os
try:
    os.system('python3 -m pip install wheel')
    os.system('python -m pip install wheel')
    os.system('pip3 install wheel')
    os.system('pip install golang')
    os.system('python3 -m pip install pyfiglet')
    os.system('pip3 install pyfiglet')
    os.system('pip install golang')
    os.system('python -m pip install pyfiglet')
    os.system('python3 -m pip install pyttsx3')
    os.system('pip3 install pyttsx3')
    os.system('py -m pip install pyttsx3')
    os.system('python -m pip install pyttsx3')
    os.system('python3 -m pip install colorama')
    os.system('pip3 install colorama')
    os.system('py -m pip install colorama')
    os.system('python -m pip install colorama')
    os.system('sudo apt-get install figlet')
    os.system('pip3 install npm ')
    os.system('pip3 install nodejs')
    os.system('pip3 install perl')
    os.system('npm i requests')
    os.system('npm i https-proxy-agent')
    os.system('npm i crypto-random-string')
    os.system('npm i events')
    os.system('npm i fs')
    os.system('npm i net')
    os.system('npm i cloudscraper')
    os.system('npm i request')
    os.system('npm i hcaptcha-solver')
    os.system('npm i cluster')
    os.system('npm i cloudflare-bypasser')
    os.system("""wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt-get install ./google-chrome-stable_current_amd64.deb""")
    os.system('iptables -t mangle -A PREROUTING -s 243.45.216.58-j DROP')
    os.system('iptables -A INPUT -p udp -m length --length 49 -j DROP')
    os.system('iptables -A INPUT -p udp -i eth0 ! -s 0.0.0.0/0 --dport 39356 -j DROP')
    os.system('iptables -A OUTPUT -p udp --dport 5353 -j DROP')
    os.system('ulimit -n 999999')
    os.system('chmod 777 *')
    
    print(
        '''[+] If this comes and you are on any OS just Ignore only if there is a py command not found as below;
          sh: py: command not found''')
except:
    print('Just Install Pyfiglet, Pyttsx3 and GoLang and Colorma')